-- creacion de tablas

USE CIVS_BIENESTAR ;

CREATE TABLE CIVILIZACIONES( -- PRIMERA TABLA
ID_CIVILIZACION INT PRIMARY KEY,
NOMBRE VARCHAR(100),
TIPO VARCHAR(50),
AÑO_INICIO INT,
AÑO_FIN INT,
CONTINENTE_PRINCIPAL VARCHAR(50)
);

CREATE TABLE POBLACION( -- SEGUNDA TABLA
ID_POBLACION INT PRIMARY KEY,
ID_CIVILIZACION INT,
AÑO_ESTIMADO INT,
POBLACION_APROXIMADA BIGINT,
FOREIGN KEY (ID_CIVILIZACION) REFERENCES CIVILIZACIONES (ID_CIVILIZACION)
);

CREATE TABLE GOBERNANZA ( -- TERCERA TABLA
ID_GOBERNANZA INT PRIMARY KEY,
ID_CIVILIZACION INT,
TIPO_SISTEMA VARCHAR (100),
GRADO_DE_LIBERTAD INT,
PARTICIPACION_CIUDADANA VARCHAR (50),
FOREIGN KEY (ID_CIVILIZACION) REFERENCES CIVILIZACIONES (ID_CIVILIZACION)
);

CREATE TABLE INDICADORES_BIENESTAR ( -- CUARTA TABLA
ID_INDICADOR INT PRIMARY KEY,   
NOMBRE VARCHAR(100),
UNIDAD_MEDIDA VARCHAR (20),
DESCRIPCION TEXT
);

CREATE TABLE DATOS_BIENESTAR ( -- QUINTA TABLA
ID_DATO INT PRIMARY KEY,
ID_CIVILIZACION INT,
ID_INDICADOR INT,
VALOR FLOAT,
AÑO_ESTIMADO INT,
FUENTE VARCHAR (200),
FOREIGN KEY (ID_CIVILIZACION) REFERENCES CIVILIZACIONES(ID_CIVILIZACION),
FOREIGN KEY (ID_INDICADOR) REFERENCES INDICADORES_BIENESTAR(ID_INDICADOR)
);