-- creacion de vistas

USE CIVS_BIENESTAR;

-- vista 1
CREATE VIEW VW_INDICADORES_POR_CIVILIZACION AS
SELECT
    c.NOMBRE AS NOMBRE_CIVILIZACION,
    i.NOMBRE AS NOMBRE_INDICADOR,
    db.VALOR,
    db.AÑO_ESTIMADO,
    db.FUENTE
FROM DATOS_BIENESTAR db
JOIN CIVILIZACIONES c ON db.ID_CIVILIZACION = c.ID_CIVILIZACION
JOIN INDICADORES_BIENESTAR i ON db.ID_INDICADOR = i.ID_INDICADOR;

SELECT * FROM VW_INDICADORES_POR_CIVILIZACION
ORDER BY NOMBRE_CIVILIZACION, NOMBRE_INDICADOR;


-- vista 2
CREATE OR REPLACE VIEW VW_PROMEDIOS_POR_TIPO_CIVILIZACION AS
SELECT
    c.TIPO AS TIPO_CIVILIZACION,
    i.NOMBRE AS NOMBRE_INDICADOR,
    i.UNIDAD_MEDIDA,
    ROUND(AVG(db.VALOR), 2) AS PROMEDIO_VALOR
FROM DATOS_BIENESTAR db
JOIN CIVILIZACIONES c ON db.ID_CIVILIZACION = c.ID_CIVILIZACION
JOIN INDICADORES_BIENESTAR i ON db.ID_INDICADOR = i.ID_INDICADOR
GROUP BY c.TIPO, i.NOMBRE, i.UNIDAD_MEDIDA
ORDER BY c.TIPO, i.NOMBRE;

SELECT * FROM VW_PROMEDIOS_POR_TIPO_CIVILIZACION

-- vista 3

CREATE OR REPLACE VIEW VW_POBLACION_MAXIMA AS
SELECT 
    c.NOMBRE AS CIVILIZACION,
    p.AÑO_ESTIMADO,
    p.POBLACION_APROXIMADA
FROM POBLACION p
JOIN CIVILIZACIONES c ON p.ID_CIVILIZACION = c.ID_CIVILIZACION
WHERE (p.ID_CIVILIZACION, p.POBLACION_APROXIMADA) IN (
    SELECT ID_CIVILIZACION, MAX(POBLACION_APROXIMADA)
    FROM POBLACION
    GROUP BY ID_CIVILIZACION
)
ORDER BY p.POBLACION_APROXIMADA DESC;

SELECT * FROM VW_POBLACION_MAXIMA;