-- creacion de triggers
 
 -- para auditar nuevos ingresos y/o modificaciones de datos a las tablas
 
 -- primero creamos una nueva tabla de auditoria
 
 CREATE TABLE AUDITORIA_GENERAL (
    ID_AUDITORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_TABLA VARCHAR(100),
    OPERACION VARCHAR(10),
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETALLE TEXT
);

-- ahora ingreso los triggers por cada tabla

DELIMITER //

-- para tabla CIVILIZACIONES

CREATE TRIGGER trg_audit_civilizaciones_insert
AFTER INSERT ON CIVILIZACIONES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, DETALLE)
    VALUES (
        'CIVILIZACIONES',
        'INSERT',
        CONCAT('ID: ', NEW.ID_CIVILIZACION, ', Nombre: ', NEW.NOMBRE, ', Tipo: ', NEW.TIPO)
    );
END;
//


CREATE TRIGGER trg_audit_civilizaciones_update
AFTER UPDATE ON CIVILIZACIONES
FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, DETALLE)
    VALUES (
        'CIVILIZACIONES',
        'UPDATE',
        CONCAT('ID: ', NEW.ID_CIVILIZACION, ', Nombre actualizado a: ', NEW.NOMBRE)
    );
END;
//

DELIMITER ;

-- prueba del trigger
SHOW TRIGGERS LIKE 'CIVILIZACIONES';

INSERT INTO CIVILIZACIONES (ID_CIVILIZACION, NOMBRE, TIPO, AÑO_INICIO, AÑO_FIN, CONTINENTE_PRINCIPAL)
VALUES (99, 'Civilización de Prueba', 'Imperio', -500, 500, 'Asia');

SELECT * FROM AUDITORIA_GENERAL
ORDER BY FECHA_HORA DESC;

-- PARA TABLA POBLACION

-- INSERT
CREATE TRIGGER tr_auditoria_insert_poblacion
AFTER INSERT ON POBLACION
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('POBLACION', 'INSERT', NOW(), 
        CONCAT('ID: ', NEW.ID_POBLACION, ', ID_CIV: ', NEW.ID_CIVILIZACION, ', Año: ', NEW.AÑO_ESTIMADO));

-- UPDATE
CREATE TRIGGER tr_auditoria_update_poblacion
AFTER UPDATE ON POBLACION
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('POBLACION', 'UPDATE', NOW(), 
        CONCAT('ID: ', NEW.ID_POBLACION, ', Año actualizado a: ', NEW.AÑO_ESTIMADO));
        
 -- PARA TABLA GOBERNANZA
 -- INSERT
CREATE TRIGGER tr_auditoria_insert_gobernanza
AFTER INSERT ON GOBERNANZA
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('GOBERNANZA', 'INSERT', NOW(), 
        CONCAT('ID: ', NEW.ID_GOBERNANZA, ', ID_CIV: ', NEW.ID_CIVILIZACION, ', Sistema: ', NEW.TIPO_SISTEMA));

-- UPDATE
CREATE TRIGGER tr_auditoria_update_gobernanza
AFTER UPDATE ON GOBERNANZA
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('GOBERNANZA', 'UPDATE', NOW(), 
        CONCAT('ID: ', NEW.ID_GOBERNANZA, ', Sistema actualizado a: ', NEW.TIPO_SISTEMA));
        
-- PARA TABLA INDICADORES_BIENESTAR
-- INSERT
CREATE TRIGGER tr_auditoria_insert_indicadores
AFTER INSERT ON INDICADORES_BIENESTAR
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('INDICADORES_BIENESTAR', 'INSERT', NOW(), 
        CONCAT('ID: ', NEW.ID_INDICADOR, ', Nombre: ', NEW.NOMBRE));

-- UPDATE
CREATE TRIGGER tr_auditoria_update_indicadores
AFTER UPDATE ON INDICADORES_BIENESTAR
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('INDICADORES_BIENESTAR', 'UPDATE', NOW(), 
        CONCAT('ID: ', NEW.ID_INDICADOR, ', Nombre actualizado a: ', NEW.NOMBRE));

-- para tabla DATOS_BIENESTAR
-- INSERT
CREATE TRIGGER tr_auditoria_insert_datos
AFTER INSERT ON DATOS_BIENESTAR
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('DATOS_BIENESTAR', 'INSERT', NOW(), 
        CONCAT('ID: ', NEW.ID_DATO, ', ID_CIV: ', NEW.ID_CIVILIZACION, ', ID_IND: ', NEW.ID_INDICADOR, ', VALOR: ', NEW.VALOR));

-- UPDATE
CREATE TRIGGER tr_auditoria_update_datos
AFTER UPDATE ON DATOS_BIENESTAR
FOR EACH ROW
INSERT INTO AUDITORIA_GENERAL (NOMBRE_TABLA, OPERACION, FECHA_HORA, DETALLE)
VALUES ('DATOS_BIENESTAR', 'UPDATE', NOW(), 
        CONCAT('ID: ', NEW.ID_DATO, ', Valor actualizado a: ', NEW.VALOR));
        
